/* Generated By:JavaCC: Do not edit this line. EG1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EG1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPEN = 4;
  /** RegularExpression Id. */
  int CLOSE = 5;
  /** RegularExpression Id. */
  int SEPARATOR = 6;
  /** RegularExpression Id. */
  int QUOTES = 7;
  /** RegularExpression Id. */
  int OR = 8;
  /** RegularExpression Id. */
  int EOL = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int EMPTY = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"<\"",
    "\">\"",
    "\"::=\"",
    "\"\\\"\"",
    "\"|\"",
    "\"\\n\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<STRING>",
    "<EMPTY>",
  };

}
